### ISSUE TITLE
as.neuronlistfh not overwriting filehash database when one already exists

### ISSUE THREAD

**Issue by alexanderbates** [jefferis/testlazyneuronlist#1]
For example, in the `lhns` package

`as.neuronlistfh(most.lhns,dbdir = 'inst/extdata/data/', WriteObjects="yes")`

Does not overwrite files stored in 'inst/extdata/data/'

**Comment by alexanderbates** [comment]
Sorry, the files are being overwritten but when I load `most.lhns` changed I have made are not appearing in its meta-data

**Comment by jefferis** [comment]
Could you be a bit more specific about what you have done? I think that the problem is that the documentation is not clear. 

`as.neuronlistfh` only makes an in memory metadata (`neuronlistfh`) object and writes the implied neuron data files to disk. It does not save the `neuronlistfh` object. To do that you have to use `write.neuronlistfh`. It would probably make sense to combine all of this into a single function for your use case.
